### ISSUE TITLE
Поломка компонентов

### ISSUE THREAD

**Issue by Elmina241** [Elmina241/MiningClicker#11]
Каждые 100 заполнений прогресс бара проверять, сломались ли компоненты

**Comment by Elmina241** [comment]
Если компонент куплен, менять иконку галочки напротив него на зеленую (Сделаю сам и покажу, как она будет меняться по кнопке. Потом просто привязать событие isBought).

**Comment by justtardis** [comment]
Галочку сделал, на ней висит код. Обновлен префаб. Осталось привязать событие isBought
