### ISSUE TITLE
Правки

### ISSUE THREAD

**Issue by Elmina241** [Elmina241/MiningClicker#12]
- Проценты с 50 не уменьшаются при покупке улучшений. 
- не изменяются значения доходности, если куплено улучшение, средней прибыли и времени
- надо скрывать текст "компоненты компьютера", если компонентов нет у ноута
- подправить отображение баланса до 2х знаков после запятой
Сделать передачу картинки компа и фона под ней в окно улучшений. Фон надо задавать в массиве спрайтов, например, и уже его тягать в окно улучшений

**Comment by justtardis** [comment]
- добавить цену покупки автомайнера ($50 у ноутбука, у всех остальных ценник  в 1.6 раза больше, чем у предыдущего компьютера
- Если компонент куплен, менять иконку галочки напротив него на зеленую (Сделаю сам и покажу, как она будет меняться по кнопке. Потом просто привязать событие isBought).

**Comment by justtardis** [comment]
Завершено
